version: "3"
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bundle", "exec", "puma", "-b", "unix:/app/sockets/puma.sock"]
    volumes:
      - .:/app
      - ./log:/app/log
      - bundle:/bundle
      - public:/app/public
      - sockets:/app/sockets
    ports:
      - "3000:3000"
    depends_on:
      - db
      - nginx
  db:
    image: postgres
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=merc
      - POSTGRES_PASSWORD=password
  nginx:
    image: nginx:1.18
    ports:
      - "80:80"
    command: [nginx]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - log:/var/log/nginx
      - sockets:/app/sockets
volumes:
  postgresql-volume:
    external: true
  bundle:
  public:
  log:
  sockets:
