version: "3"
services: 
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=merc
      - POSTGRES_PASSWORD=password
volumes:
  postgresql-volume:
    external: true